spring.application.name=ipl-auction-backend

server.port=${PORT:8084}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.jpdryxehntfxarbnofzv
#spring.datasource.password=rbSUND@R@JAN3456

#google oauth config
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-id=495297066862-v2jdi3k4cft247kmig9l4kk5r5m7enjr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.liquibase=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never