--liquibase formatted sql

--changeset ipl-auction:002-create-players

CREATE TABLE players (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cricsheet_player_id VARCHAR(20) NOT NULL UNIQUE,
                         name VARCHAR(150) NOT NULL,
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);