--liquibase formatted sql

--changeset ipl-auction:004-create-team-aliases

CREATE TABLE team_aliases (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              team_id BIGINT NOT NULL,

                              alias_name VARCHAR(100) NOT NULL,

                              valid_from_season VARCHAR(10) NOT NULL,
                              valid_to_season VARCHAR(10),

                              CONSTRAINT fk_team_aliases_team
                                  FOREIGN KEY (team_id)
                                      REFERENCES teams(id),

                              CONSTRAINT uq_team_alias
                                  UNIQUE (team_id, alias_name)
);