--liquibase formatted sql

--changeset ipl-auction:007-create-venues

CREATE TABLE venues (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        name VARCHAR(200) NOT NULL,

                        city VARCHAR(100),

                        country VARCHAR(100),

                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uq_venue_name_city
                            UNIQUE (name, city)
);