--liquibase formatted sql

--changeset ipl-auction:008-create-venue-aliases

CREATE TABLE venue_aliases (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               venue_id BIGINT NOT NULL,

                               alias_name VARCHAR(200) NOT NULL,

                               alias_city VARCHAR(100),

                               CONSTRAINT fk_venue_aliases_venue
                                   FOREIGN KEY (venue_id)
                                       REFERENCES venues(id),

                               CONSTRAINT uq_venue_alias
                                   UNIQUE (alias_name, alias_city)
);