--liquibase formatted sql

--changeset ipl-auction:009-seed-venues

INSERT INTO venues (name, city, country) VALUES
                                             ('Eden Gardens', 'Kolkata', 'India'),
                                             ('Wankhede Stadium', 'Mumbai', 'India'),
                                             ('M Chinnaswamy Stadium', 'Bengaluru', 'India'),
                                             ('Arun Jaitley Stadium', 'Delhi', 'India'),
                                             ('Rajiv Gandhi International Stadium', 'Hyderabad', 'India'),
                                             ('MA Chidambaram Stadium', 'Chennai', 'India'),
                                             ('Sawai Mansingh Stadium', 'Jaipur', 'India'),
                                             ('Dubai International Cricket Stadium', 'Dubai', 'United Arab Emirates'),
                                             ('Narendra Modi Stadium', 'Ahmedabad', 'India'),
                                             ('Punjab Cricket Association IS Bindra Stadium', 'Mohali', 'India'),
                                             ('Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow', 'Lucknow', 'India'),
                                             ('Sheikh Zayed Stadium', 'Abu Dhabi', 'United Arab Emirates'),
                                             ('Sharjah Cricket Stadium', 'Sharjah', 'United Arab Emirates'),
                                             ('Maharashtra Cricket Association Stadium', 'Pune', 'India'),
                                             ('Dr DY Patil Sports Academy', 'Navi Mumbai', 'India'),
                                             ('Brabourne Stadium', 'Mumbai', 'India'),
                                             ('Kingsmead', 'Durban', 'South Africa'),
                                             ('Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Visakhapatnam', 'India'),
                                             ('SuperSport Park', 'Centurion', 'South Africa'),
                                             ('Himachal Pradesh Cricket Association Stadium', 'Dharamsala', 'India'),
                                             ('Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'New Chandigarh', 'India'),
                                             ('Saurashtra Cricket Association Stadium', 'Rajkot', 'India'),
                                             ('Holkar Cricket Stadium', 'Indore', 'India'),
                                             ('Barsapara Cricket Stadium', 'Guwahati', 'India'),
                                             ('New Wanderers Stadium', 'Johannesburg', 'South Africa'),
                                             ('Barabati Stadium', 'Cuttack', 'India'),
                                             ('JSCA International Stadium Complex', 'Ranchi', 'India'),
                                             ('Newlands', 'Cape Town', 'South Africa'),
                                             ('St George''s Park', 'Port Elizabeth', 'South Africa'),
                                             ('Shaheed Veer Narayan Singh International Stadium', 'Raipur', 'India'),
                                             ('Nehru Stadium', 'Kochi', 'India'),
                                             ('Green Park', 'Kanpur', 'India'),
                                             ('Buffalo Park', 'East London', 'South Africa'),
                                             ('De Beers Diamond Oval', 'Kimberley', 'South Africa'),
                                             ('Vidarbha Cricket Association Stadium, Jamtha', 'Nagpur', 'India'),
                                             ('OUTsurance Oval', 'Bloemfontein', 'South Africa');