--liquibase formatted sql

--changeset ipl-auction:011-create-matches

CREATE TABLE matches (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         source_match_id BIGINT NOT NULL UNIQUE,

                         season VARCHAR(10) NOT NULL,

                         match_date DATE NOT NULL,

                         city VARCHAR(100),

                         venue_id BIGINT NOT NULL,

                         team_1_id BIGINT NOT NULL,

                         team_2_id BIGINT NOT NULL,

                         toss_winner_team_id BIGINT,

                         toss_decision VARCHAR(10) NOT NULL,

                         winner_team_id BIGINT,

                         result_type VARCHAR(30),

                         result_margin INTEGER,

                         player_of_match_id BIGINT,

                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT fk_matches_venue
                             FOREIGN KEY (venue_id)
                                 REFERENCES venues(id),

                         CONSTRAINT fk_matches_team_1
                             FOREIGN KEY (team_1_id)
                                 REFERENCES teams(id),

                         CONSTRAINT fk_matches_team_2
                             FOREIGN KEY (team_2_id)
                                 REFERENCES teams(id),

                         CONSTRAINT fk_matches_toss_winner
                             FOREIGN KEY (toss_winner_team_id)
                                 REFERENCES teams(id),

                         CONSTRAINT fk_matches_winner
                             FOREIGN KEY (winner_team_id)
                                 REFERENCES teams(id),

                         CONSTRAINT fk_matches_player_of_match
                             FOREIGN KEY (player_of_match_id)
                                 REFERENCES players(id),

                         CONSTRAINT chk_matches_teams_different
                             CHECK (team_1_id <> team_2_id),

                         CONSTRAINT chk_matches_toss_decision
                             CHECK (toss_decision IN ('bat', 'field')),

                         CONSTRAINT chk_matches_result_type
                             CHECK (
                                 result_type IS NULL
                                     OR result_type IN (
                                                        'WON_BY_RUNS',
                                                        'WON_BY_WICKETS',
                                                        'TIED',
                                                        'NO_RESULT'
                                     )
                                 ),

                         CONSTRAINT chk_matches_result_margin
                             CHECK (
                                 result_margin IS NULL
                                     OR result_margin >= 0
                                 )
);