--liquibase formatted sql

--changeset ipl-auction:012-create-player-match-stats

CREATE TABLE player_match_stats (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    match_id BIGINT NOT NULL,
                                    player_id BIGINT NOT NULL,
                                    team_id BIGINT NOT NULL,

                                    batting_innings INTEGER NOT NULL DEFAULT 0,
                                    runs INTEGER NOT NULL DEFAULT 0,
                                    balls_faced INTEGER NOT NULL DEFAULT 0,
                                    fours INTEGER NOT NULL DEFAULT 0,
                                    sixes INTEGER NOT NULL DEFAULT 0,
                                    dismissals INTEGER NOT NULL DEFAULT 0,

                                    bowling_innings INTEGER NOT NULL DEFAULT 0,
                                    runs_conceded INTEGER NOT NULL DEFAULT 0,
                                    balls_bowled INTEGER NOT NULL DEFAULT 0,
                                    wickets INTEGER NOT NULL DEFAULT 0,
                                    maidens INTEGER NOT NULL DEFAULT 0,

                                    catches INTEGER NOT NULL DEFAULT 0,
                                    stumpings INTEGER NOT NULL DEFAULT 0,
                                    run_outs INTEGER NOT NULL DEFAULT 0,

                                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CONSTRAINT fk_player_match_stats_match
                                        FOREIGN KEY (match_id)
                                            REFERENCES matches(id),

                                    CONSTRAINT fk_player_match_stats_player
                                        FOREIGN KEY (player_id)
                                            REFERENCES players(id),

                                    CONSTRAINT fk_player_match_stats_team
                                        FOREIGN KEY (team_id)
                                            REFERENCES teams(id),

                                    CONSTRAINT uq_player_match_stats
                                        UNIQUE (match_id, player_id)
);