--liquibase formatted sql

--changeset ipl-auction:013-create-auctions

CREATE TABLE auctions (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(200) NOT NULL,
                          season VARCHAR(10) NOT NULL,
                          status VARCHAR(20) NOT NULL,
                          starting_purse BIGINT NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT chk_auction_status
                              CHECK (status IN ('CREATED', 'READY', 'LIVE', 'COMPLETED')),

                          CONSTRAINT chk_auction_starting_purse
                              CHECK (starting_purse > 0)
);