--liquibase formatted sql

--changeset ipl-auction:014-create-auction-teams

CREATE TABLE auction_teams (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               auction_id BIGINT NOT NULL,
                               team_id BIGINT NOT NULL,

                               starting_purse BIGINT NOT NULL,
                               remaining_purse BIGINT NOT NULL,

                               created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_auction_teams_auction
                                   FOREIGN KEY (auction_id)
                                       REFERENCES auctions(id),

                               CONSTRAINT fk_auction_teams_team
                                   FOREIGN KEY (team_id)
                                       REFERENCES teams(id),

                               CONSTRAINT uq_auction_teams_auction_team
                                   UNIQUE (auction_id, team_id),

                               CONSTRAINT chk_auction_teams_starting_purse
                                   CHECK (starting_purse > 0),

                               CONSTRAINT chk_auction_teams_remaining_purse
                                   CHECK (remaining_purse >= 0),

                               CONSTRAINT chk_auction_teams_remaining_purse_limit
                                   CHECK (remaining_purse <= starting_purse)
);