--liquibase formatted sql

--changeset ipl-auction:015-create-auction-players

CREATE TABLE auction_players (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 auction_id BIGINT NOT NULL,
                                 player_id BIGINT NOT NULL,

                                 base_price BIGINT NOT NULL,
                                 status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED',

                                 sold_to_auction_team_id BIGINT,
                                 sold_price BIGINT,

                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_auction_players_auction
                                     FOREIGN KEY (auction_id)
                                         REFERENCES auctions(id),

                                 CONSTRAINT fk_auction_players_player
                                     FOREIGN KEY (player_id)
                                         REFERENCES players(id),

                                 CONSTRAINT fk_auction_players_sold_to_team
                                     FOREIGN KEY (sold_to_auction_team_id)
                                         REFERENCES auction_teams(id),

                                 CONSTRAINT uq_auction_players_auction_player
                                     UNIQUE (auction_id, player_id),

                                 CONSTRAINT chk_auction_players_status
                                     CHECK (status IN ('REGISTERED', 'SOLD', 'UNSOLD')),

                                 CONSTRAINT chk_auction_players_base_price
                                     CHECK (base_price > 0),

                                 CONSTRAINT chk_auction_players_sold_price
                                     CHECK (sold_price IS NULL OR sold_price > 0)
);