--liquibase formatted sql

--changeset ipl-auction:018-create-auction-bids

CREATE TABLE auction_bids (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              auction_id BIGINT NOT NULL,
                              auction_player_id BIGINT NOT NULL,
                              auction_team_id BIGINT NOT NULL,

                              amount BIGINT NOT NULL,

                              created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_auction_bids_auction
                                  FOREIGN KEY (auction_id) REFERENCES auctions(id),

                              CONSTRAINT fk_auction_bids_player
                                  FOREIGN KEY (auction_player_id) REFERENCES auction_players(id),

                              CONSTRAINT fk_auction_bids_team
                                  FOREIGN KEY (auction_team_id) REFERENCES auction_teams(id),

                              CONSTRAINT chk_auction_bids_amount
                                  CHECK (amount > 0)
);